### PR TITLE
aded inline buttons for character selection, and model selector with /models command

### PR DESCRIPTION
**Pull request by GalvareyPoco**

### CODE REVIEW

**Comment by innightwolfsleep** [comment]
Model changing option broke something. Perhaps, extensions shouldnt do "import server" (seems, this import running loads of second model instance to GPU)

**Comment by GalvareyPoco** [comment]
> Model changing option broke something. Perhaps, extensions shouldnt do "import server" (seems, this import running loads of second model instance to GPU)

can you send me a log of what broke on model changing? local testing worked fine with ggml models and 4bit models

**Comment by innightwolfsleep** [comment]
I found a problem - oobabooga/text-generation-webui was slightly updated, extension work after text-generation-webui full reinstalled.
I ready to merge, but we have conflits in script.py now (character loading, i think). 
Can you update your branch and merge again?

**Comment by GalvareyPoco** [comment]
> I found a problem - oobabooga/text-generation-webui was slightly updated, extension work after text-generation-webui full reinstalled. I ready to merge, but we have conflits in script.py now (character loading, i think). Can you update your branch and merge again?
> 
> p.s. still have problem with models switching, but it is seems my resources shortrage problem.

it should work now i think, just test it please, also you might want to start the models with the --pre-layer parameter, it should work to use less vram when loading models

**Pull request merged**
